# Generated by Django 4.0.5 on 2023-10-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProvincia', models.CharField(max_length=100)),
                ('fkPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('fk_Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais')),
                ('fk_Provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.provincia')),
            ],
        ),
    ]
